presubmits:
  - name: presubmit-esa-test
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:6
        command:
        - make
        args:
        - test
  - name: presubmit-esa-license-header-check
    decorate: true
    always_run: true
    spec:
      containers:
      - image: nephio/gotests:1671656214984921088
        command:
        - "/bin/sh"
        - "-c"
        - |
          /usr/local/bin/checklicense.sh > ${ARTIFACTS}/license_headers_results.txt
  - name: presubmit-esa-scancode-toolkit
    decorate: true
    always_run: true
    spec:
      containers:
      - image: nephio/scancode-toolkit:v31.2.5
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          /scancode-toolkit/scancode --ignore "whitelist.json" -clpeui -n 2 --html ${ARTIFACTS}/scancode_report.html . --tallies-with-details
        resources:
          requests:
            cpu: 2
            memory: 1Gi
  - name: presubmit-esa-fossology
    decorate: true
    always_run: true
    spec:
      containers:
      - image: fossology/fossology:scanner
        command:
        - "/bin/bash"
        args:
        - "-c"
        - |
          /bin/fossologyscanner repo nomos ojo copyright keyword
          cp -R results ${ARTIFACTS}/    
  - name: presubmit-esa-lichen
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:1671656214984921088
        command:
        - "/usr/local/bin/lichen.sh"
