presubmits:
  - name: presubmit-esa-test
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:5
        command:
        - make
        args:
        - test